// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yivaqmuhnfhzuarcujio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpdmFxbXVobmZoenVhcmN1amlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Njk1OTMsImV4cCI6MjA2NzM0NTU5M30.xn8faitRcPo79yqNVLDlm3S111DoRxNuP3XfWbwBOaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'Content-Profile': 'public',
      'Accept-Profile': 'public'
    }
  }
});